import json
import re
from typing import Any

from pydantic import BaseModel, Field, ValidationError

from research_pilot.core.llm_client import OpenAICompatibleLLMClient
from research_pilot.core.todo import TodoItem, TodoList, TodoStatus


class ResearchSubTask(BaseModel):
    """One research subtask generated by the planner."""

    id: str
    title: str
    query: str
    rationale: str | None = None


class ResearchPlan(BaseModel):
    """A research plan containing several subtasks."""

    topic: str
    tasks: list[ResearchSubTask] = Field(default_factory=list)


class ResearchPlannerAgent:
    """A specialized planner for deep research tasks.

    This is similar in spirit to the TODO Planner in Hello Agents Chapter 14.
    It decomposes a broad research topic into concrete searchable subtasks.
    """

    def __init__(self, llm_client: OpenAICompatibleLLMClient):
        self.llm_client = llm_client

    def plan(self, topic: str) -> ResearchPlan:
        messages = [
            {
                "role": "system",
                "content": self._system_prompt(),
            },
            {
                "role": "user",
                "content": f"Research topic:\n{topic}",
            },
        ]

        raw_output = self.llm_client.complete(messages)

        try:
            payload = self._extract_json(raw_output)
            plan = ResearchPlan.model_validate(payload)

            if not plan.tasks:
                return self._fallback_plan(topic)

            return plan

        except (json.JSONDecodeError, ValidationError, ValueError, TypeError):
            return self._fallback_plan(topic)

    def to_todo_list(self, plan: ResearchPlan) -> TodoList:
        """Convert a research plan into a runtime todo list."""

        items: list[TodoItem] = []

        for task in plan.tasks:
            items.append(
                TodoItem(
                    id=task.id,
                    content=f"Research: {task.title}",
                    status=TodoStatus.PENDING,
                    notes=f"Search query: {task.query}",
                )
            )

        items.append(
            TodoItem(
                id="report",
                content="Write and save the final research report",
                status=TodoStatus.PENDING,
                notes="Use save_report after collecting enough evidence.",
            )
        )

        return TodoList(items=items)

    def _system_prompt(self) -> str:
        return """You are a research planning agent.

Your job is to decompose a broad research topic into 3 to 5 concrete research subtasks.

You must return exactly one JSON object.
Do not use markdown.
Do not wrap JSON in code fences.
Do not add explanations outside JSON.

The JSON schema is:

{
  "topic": "original research topic",
  "tasks": [
    {
      "id": "1",
      "title": "short subtask title",
      "query": "search query for this subtask",
      "rationale": "why this subtask is useful"
    }
  ]
}

Rules:
- Generate 3 to 5 subtasks.
- Each subtask should be searchable.
- Use concise titles.
- Use concrete queries.
- Do not include final report writing as a research subtask.
"""

    def _extract_json(self, text: str) -> dict[str, Any]:
        stripped = text.strip()

        if stripped.startswith("{") and stripped.endswith("}"):
            return json.loads(stripped)

        fence_match = re.search(
            r"```(?:json)?\s*(\{.*?\})\s*```",
            stripped,
            flags=re.DOTALL,
        )
        if fence_match:
            return json.loads(fence_match.group(1))

        object_match = re.search(r"(\{.*\})", stripped, flags=re.DOTALL)
        if object_match:
            return json.loads(object_match.group(1))

        raise json.JSONDecodeError("No JSON object found", stripped, 0)

    def _fallback_plan(self, topic: str) -> ResearchPlan:
        """Fallback planner when LLM planning fails."""

        return ResearchPlan(
            topic=topic,
            tasks=[
                ResearchSubTask(
                    id="1",
                    title="Understand the basic concept",
                    query=f"{topic} definition overview",
                    rationale="Start by clarifying the basic concept.",
                ),
                ResearchSubTask(
                    id="2",
                    title="Identify main methods or architectures",
                    query=f"{topic} methods architecture",
                    rationale="Find the main technical approaches.",
                ),
                ResearchSubTask(
                    id="3",
                    title="Summarize applications and challenges",
                    query=f"{topic} applications challenges",
                    rationale="Understand practical use cases and limitations.",
                ),
            ],
        )